# Generated by Django 4.1.1 on 2022-10-28 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0005_subscriberscategory_category_subscribers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriberscategory',
            old_name='subscribers',
            new_name='user',
        ),
    ]
